// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv

import { defineConfig } from "prisma/config";
import { env } from "@/infra/env/index.js";

const databaseUrl = env.DATABASE_URL;

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    url: databaseUrl,
  },
});
